---
title: <center> Financial Products and Markets -- Groupwork </center> 
author: <center> Santiago Greloni, Gaspar Suliansky, Wiem Touzi </center>
date: ""
output: html_document
---

***

### 1. Load libraries

```{r message = FALSE} 
library(tidyverse)
library(readxl)
library(ggthemes)
```

***

### 2. Load datasets

```{r}
data_1 <- read_xlsx("/Users/gasparsuliansky/Desktop/Financial Products and Markets/Group work/Data.xlsx") # Original data
data_2 <- read_xlsx("/Users/gasparsuliansky/Desktop/Financial Products and Markets/Group work/Data_smoothed.xlsx") # Smoothed data (Exponentially Weighted Average)
```

***

### 3. Tidy & merge datasets

```{r message = FALSE}
data_1 <- data_1 %>% 
  pivot_longer(2:4, 
               names_to = "Company",
               values_to = "Bond Spreads")
data_2 <- data_2 %>% 
  pivot_longer(2:4, 
               names_to = "Company",
               values_to = "Bond Spreads (Expontentially Weighted Average)") 
data <- full_join(data_1, data_2) 
```

***

### 4. Plot data

```{r fig.align = "center"}
data %>%
  pivot_longer(3:4, 
               names_to = "Variables",
               values_to = "Values") %>%
  ggplot(aes(x = as.Date(Date),
             y = Values,
             col = Company)) +
  geom_hline(yintercept = 0,
             col = "black",
             linetype = "dashed",
             size = 0.25) +
  geom_line(size = 0.75) +
  scale_y_continuous(limits = c(0, 150),
                     n.breaks = 4,
                     labels = scales::label_number(suffix = " (bps)"),
                     sec.axis = dup_axis()) +
  scale_x_date(date_labels = "%b %Y",
               breaks = "1 month") + 
  scale_color_manual(values = c(`AKZO NOBEL N.V.` = "#132453",
                                `BAYER AG` = "#a5c1c4",
                                `KONINKLIJKE KPN N.V.` = "#d6bc79")) +
  facet_wrap(~ Variables,
             ncol = 1) +
  theme_base() + 
  labs(x = "",
       y = "") +
  theme(legend.position = "bottom", 
        legend.title = element_blank(),
        legend.text = element_text(family = "Times",
                                   size = 9),
        text = element_text(family = "Times",
                            hjust = 0.5),
        axis.text = element_text(colour = "black",
                                 size = 10,
                                 hjust = 0.5),
        axis.text.x = element_text(margin = margin(t = 15, r = 0, b = 0, l = 0),
                                   angle = 90),
        axis.ticks.y = element_blank(),
        legend.box.background = element_rect(colour = "black"))
```
